frameworks:
  - name: crescendo
    max_turns: 10
    n_attempts_per_objective: 10

  - name: actorattack
    max_turns: 10
    n_attempts_per_objective: 10

  - name: xteaming
    max_turns: 10
    n_attempts_per_objective: 10

behaviors_dataset: JBB-Behaviors
n_objectives: 100

verdicts:
  - jailbroken
  - refusal
  - near_miss
  - benign
